# Generated by Django 4.1.1 on 2022-09-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField()),
                ('privacy', models.CharField(max_length=50)),
            ],
        ),
    ]
