# Generated by Django 4.1.1 on 2022-09-18 18:20

from django.db import migrations
from datetime import datetime

def create_data(apps, schema_editor):
    Post = apps.get_model('website', 'Post')

    Post(user="mauricio", 
    content="This is the first post", 
    date_posted= datetime.strptime("01/01/2022","%d/%m/%Y"), 
    privacy="public").save()


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
