# Generated by Django 4.1.1 on 2022-09-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_comment_date_posted_alter_post_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
