# Generated by Django 3.2.16 on 2022-10-06 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='from_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='website.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='to_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='website.user'),
            preserve_default=False,
        ),
    ]
