# Generated by Django 3.2.16 on 2022-11-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20221010_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction_type',
            name='svg',
            field=models.TextField(default=''),
        ),
    ]
